In [ ]:
from google.colab import drive    #mounting to google drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/network-logs.csv")

In [ ]:
df

REMOTE_PORT    LATENCY  THROUGHPUT  ANOMALY
0             21  15.942875   16.202998        0
1             20  12.666451   15.899084        1
2             80  13.894550   12.958008        0
3             21  13.620813   15.459475        0
4             21  15.705485   15.339565        0
..           ...        ...         ...      ...
400           21  15.068575   15.623643        0
401           21  15.888901   16.337056        0
402           80  14.076014   15.842064        0
403          443  10.882213   13.461662        0
404           21  14.009203   15.976576        0

[405 rows x 4 columns]

In [ ]:
#Shape of the data
df.shape

(405, 4)

In [ ]:
df.describe()

REMOTE_PORT     LATENCY  THROUGHPUT     ANOMALY
count   405.000000  405.000000  405.000000  405.000000
mean     63.555556   14.420702   15.392091    0.029630
std     106.300247    1.449806    1.172879    0.169773
min      20.000000    4.752613    4.126232    0.000000
25%      21.000000   13.408520   15.223188    0.000000
50%      21.000000   15.014320   15.572503    0.000000
75%      80.000000   15.489068   15.868064    0.000000
max     443.000000   23.339868   24.350407    1.000000

In [ ]:
df.columns

Index(['REMOTE_PORT', 'LATENCY', 'THROUGHPUT', 'ANOMALY'], dtype='object')

In [ ]:
#Datatypes
df.dtypes

REMOTE_PORT      int64
LATENCY        float64
THROUGHPUT     float64
ANOMALY          int64
dtype: object

In [ ]:
X=df.iloc[:,1:-1].values #remove the predictor 

In [ ]:
y=df.iloc[:,-1].values #response variable

In [ ]:
#X.head()

In [ ]:
X

array([[15.94287532, 16.20299807],
       [12.66645095, 15.89908374],
       [13.89454962, 12.95800822],
       [13.62081292, 15.45947525],
       [15.70548485, 15.33956527],
       [15.59318973, 15.61238106],
       [15.48906755, 15.64087368],
       [15.52704801, 15.63568031],
       [14.07506707, 15.76531533],
       [12.95364954, 15.82328512],
       [12.88787444, 15.0760781 ],
       [16.02178961, 16.25746992],
       [15.92629271, 16.29725072],
       [12.465594  , 15.16321212],
       [15.08466278, 15.44192203],
       [15.53717523, 15.24224248],
       [15.22250852, 15.42386188],
       [15.51908496, 14.09871699],
       [13.11971434, 15.66081846],
       [13.04681517, 15.74115241],
       [13.40852019, 13.7632696 ],
       [15.19591481, 15.85318113],
       [15.91470077, 16.17425987],
       [13.57669961, 15.04284944],
       [14.02240251, 13.40646894],
       [12.82213164, 15.22318782],
       [15.67636615, 15.89169137],
       [15.94287532, 16.20299807],
       [12.66645095,

In [ ]:
X.shape

(405, 2)

In [ ]:
y.shape #anomaly

(405,)

In [ ]:
X=X.astype("int")

In [ ]:
y=y.astype("int")

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#X_train,X_test,y_train,y_test=train_test_split(df,test_size=0.2,random_state=42)
#Split X and y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(324, 2) (81, 2) (324,) (81,)


In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_Default=SVC()
svm_Default.fit(X_train,y_train)
y_pred_SVM_Default=svm_Default.predict(X_test)

In [ ]:
SVM_Default_Accuracy=100.0* accuracy_score(y_test,y_pred_SVM_Default)
print("SVM Default Kernel Accuracy:" ,str(SVM_Default_Accuracy))

SVM Default Kernel Accuracy: 97.53086419753086


In [ ]:
svm_Linear=SVC(kernel='linear',C=1.0 ,random_state=42)
svm_Linear.fit(X_train,y_train)
y_pred_SVM_Linear=svm_Linear.predict(X_test)

In [ ]:
SVM_Linear_Accuracy=100.0* accuracy_score(y_test,y_pred_SVM_Linear)
print("SVM Default Kernel Accuracy:" ,str(SVM_Linear_Accuracy))

SVM Default Kernel Accuracy: 97.53086419753086


In [ ]:
svm_Poly=SVC(kernel='poly',degree=1.0,gamma=1)
svm_Poly.fit(X_train,y_train)
y_pred_SVM_Poly=svm_Poly.predict(X_test)

In [ ]:
SVM_Poly_Accuracy = 100.00* accuracy_score(y_test,y_pred_SVM_Poly)
print("SVM Poly Kernel Accuracy:" ,str(SVM_Poly_Accuracy))

SVM Poly Kernel Accuracy: 97.53086419753086


In [ ]:
svm_Sigmoid=SVC(kernel='sigmoid',degree=1.0,random_state=42)
svm_Sigmoid.fit(X_train,y_train)
y_pred_SVM_Sigmoid=svm_Sigmoid.predict(X_test)

In [ ]:
SVM_Sigmoid_Accuracy = 100.00*accuracy_score(y_test,y_pred_SVM_Sigmoid)
print("SVM Poly Kernel Accuracy:" ,str(SVM_Sigmoid_Accuracy))

SVM Poly Kernel Accuracy: 97.53086419753086


**SVM Results**

In [ ]:
SVM_Default_Accuracy


97.53086419753086

In [ ]:
SVM_Linear_Accuracy


97.53086419753086

In [ ]:
SVM_Poly_Accuracy


97.53086419753086

In [ ]:
SVM_Sigmoid_Accuracy

97.53086419753086

In [ ]:
# Random Forest Classifier

classifier_RF = RandomForestClassifier()
# Train the classifier
classifier_RF.fit(nX_train, y_train.ravel())

# Predict test data
y_test_predict = classifier_RF.predict(nX_test)

# Get the classification report
accuracy = accuracy_score(y_test, y_test_predict) * 100
print(classification_report(y_test, y_test_predict, target_names=health_label))
print("Accuracy: " + str(accuracy) + '%')

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_SVM_Default))
print(classification_report(y_test, y_pred_SVM_Default))

[[76  0]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        76
           1       0.00      0.00      0.00         5

    accuracy                           0.94        81
   macro avg       0.47      0.50      0.48        81
weighted avg       0.88      0.94      0.91        81



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_SVM_Default))
print(classification_report(y_test, y_pred_SVM_Default))

[[76  0]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        76
           1       0.00      0.00      0.00         5

    accuracy                           0.94        81
   macro avg       0.47      0.50      0.48        81
weighted avg       0.88      0.94      0.91        81



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_SVM_Poly))
print(classification_report(y_test,y_pred_SVM_Poly))


[[76  0]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        76
           1       0.00      0.00      0.00         5

    accuracy                           0.94        81
   macro avg       0.47      0.50      0.48        81
weighted avg       0.88      0.94      0.91        81



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_SVM_Linear))
print(classification_report(y_test,y_pred_SVM_Linear))

[[79  0]
 [ 2  0]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        79
           1       0.00      0.00      0.00         2

    accuracy                           0.98        81
   macro avg       0.49      0.50      0.49        81
weighted avg       0.95      0.98      0.96        81



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_SVM_Sigmoid))
print(classification_report(y_test,y_pred_SVM_Sigmoid))

[[79  0]
 [ 2  0]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        79
           1       0.00      0.00      0.00         2

    accuracy                           0.98        81
   macro avg       0.49      0.50      0.49        81
weighted avg       0.95      0.98      0.96        81



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Linear Regression**

 **Test Results**

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:

from sklearn.feature_selection import SequentialFeatureSelector as SFS
import statsmodels.api as sm  #Import Statsmodel library

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectFromModel
#sklearn.feature_selection.SelectKBest

In [ ]:
X_new =SelectKBest(chi2,k=3)


In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [ ]:
#fit your models
lr.fit(X_train,y_train)

In [ ]:
from sklearn import linear_model
ls=linear_model.Lasso(alpha=0.1)
ls.fit(X_train,y_train)

In [ ]:
from sklearn.linear_model import LinearRegression 
#Regression model
model = LinearRegression()
model.fit(X_train,y_train)
print(model.score(X_test,y_test))


In [ ]:
#Make Prediction
y_pred_SVM_Default=lr.predict(X_test)

In [ ]:
#Performance Evaluation
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
#Improving the model using backward selection by adding a dummy feature of 1
X_train = np.append (arr=np.ones(
[X_train.shape[0],1]
)
.astype(int), values = X_train, axis = 1)

In [ ]:
RMSE=pow(mean_squared_error(y_pred,y_test) ,0.5) #RMSE Regression
R=r2_score(y_pred,y_test)
print("RMSE is" ,RMSE)
print("R squared is" ,R)

In [ ]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_SVM_Poly)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_SVM_Poly))
